routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
define('STDIN',fopen("php://stdin","r"));
Route::get('install', function() {
    Artisan::call('migrate',['--force'=>true,'--seed'=>true]);
});
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::namespace('admin')->name('admin.')->middleware(['auth'])->group(function(){
    Route::get('/admin/triage-diario-index', 'DailyTriageController@index')->name('triage');
    Route::get('/admin/traige-diario-review-/{date?}', 'DailyTriageController@review')->name('triage.review');
    Route::get('/admin/traige-diario-filter-/{id?}', 'DailyTriageController@filter')->name('triage.filter');
    Route::get('/admin/traige-diario/estadisticas/{date?}', 'DailyTriageController@chart')->name('triage.chart');
    Route::get('/admin/traige-diario/send-email/{email}', 'DailyTriageController@sendEmail')->name('triage.send.email');
    Route::get('/admin/triage/enviar-email',function (){
        return view('admin.report.daily-check-email');
    })->name('triage.email');
    //reporte de covid
    Route::get('/admin/reporte-de-covid-19-', 'CaseReportController@index')->name('report.case');
    Route::get('/admin/reporte-de-covid-19-review/{date?}', 'CaseReportController@review')->name('report.case.review');
    Route::get('/admin/reporte-de-covid-19-filter/{id?}', 'CaseReportController@filter')->name('report.case.filter');
    
    //verificación diaria
    Route::get('/admin/verificación-diaria', 'DailyCheckController@index')->name('daily.check');
    Route::get('/admin/verificación-diaria-review', 'DailyCheckController@review')->name('daily.check.review');
    Route::get('/admin/check-si/{id}/{date}', 'DailyCheckController@reviewYes')->name('daily.check.review.yes');
    Route::get('/admin/check-no/{id}/{date}', 'DailyCheckController@reviewNo')->name('daily.check.review.no');
    Route::get('/admin/estadísticas/{date?}', 'DailyCheckController@chart')->name('daily.check.chart');
    Route::get('/admin/enviar-email',function (){
        return view('admin.report.daily-check-email');
    })->name('daily.check.email');
    Route::get('/admin/daily/send-email/{email}', 'InfoController@sendEmailDaily')->name('daily.check.send.email');

    Route::get('/admin/mi-qr', 'InfoController@myQr')->name('myqr');
    //Protocolos
    Route::get('/admin/protocolos', 'ProtocolController@index')->name('protocol');
    //Noticias
    Route::get('/admin/noticias', 'NoticeController@index')->name('notice');
    //Ficha sintomatológica
    Route::get('/admin/file', 'InfoController@file')->name('file');
    Route::get('/admin/file-review/{date?}', 'InfoController@review')->name('file.review');
    Route::get('/admin/file-filter/{id?}', 'InfoController@filter')->name('file.filter');
    Route::get('/admin/file-excel',function(){
        return view('admin.report.report-excel-send');
    })->name('file.send-excel');
    Route::get('/admin/send-email/{email}', 'InfoController@sendEmail')->name('file.send.email');

    //phone
    Route::get('admin/telefonos', 'InfoController@phone')->name('phone');
});

Route::namespace('supervisor')->name('supervisor.')->middleware(['auth'])->group(function () {
   //traige
Route::get('/supervisor/traige-diario-view', 'DailyTriageController@index')->name('triage');
Route::get('/supervisor/traige-diario-review/{date?}', 'DailyTriageController@review')->name('triage.review');
Route::get('/supervisor/traige-diario-filter/{id?}', 'DailyTriageController@filter')->name('triage.filter');

//reporte de covid
Route::get('/supervisor/reporte-de-covid-19-', 'CaseReportController@index')->name('report.case');
Route::get('/supervisor/reporte-de-covid-19-review/{date?}', 'CaseReportController@review')->name('report.case.review');
Route::get('/supervisor/reporte-de-covid-19-filter/{id?}', 'CaseReportController@filter')->name('report.case.filter');

//verificación diaria
Route::get('/supervisor/verificación-diaria', 'DailyCheckController@index')->name('daily.check');
Route::get('/supervisor/verificación-diaria-review-/{date?}', 'DailyCheckController@review')->name('daily.check.review');
Route::get('/supervisor/check-si/{id}/{date}', 'DailyCheckController@reviewYes')->name('daily.check.review.yes');
Route::get('/supervisor/check-no/{id}/{date}', 'DailyCheckController@reviewNo')->name('daily.check.review.no');

Route::get('/supervisor/mi-qr', 'InfoController@myQr')->name('myqr');
//Protocolos
Route::get('/supervisor/protocolos', 'ProtocolController@index')->name('protocol');
//Noticias
Route::get('/supervisor/noticias', 'NoticeController@index')->name('notice');
//Ficha sintomatológica
Route::get('/supervisor/file', 'InfoController@file')->name('file');
Route::get('/supervisor/file-review/{date?}', 'InfoController@review')->name('file.review');
Route::get('/supervisor/file-filter/{id?}', 'InfoController@filter')->name('file.filter');



Route::get('/lector-qr', 'InfoController@lectorQr')->name('lector.qr');
Route::post('/guardar-qr', 'InfoController@saveQr')->name('store.qr');
Route::get('/historial-qr/{date?}', 'InfoController@reviewQr')->name('qr.review');


});
/*Route::namespace('supervisor')->middleware(['auth','supervisor'])->group(function(){


});*/

Route::get('/home', 'HomeController@panel')->name('home');
Route::get('/admin', 'HomeController@admin')->name('admin');
Route::get('/supervisor', 'HomeController@supervisor')->name('supervisor');
Route::get('/inicio', 'HomeController@usuario')->name('usuario');

//traige
Route::get('/traige-diario-', 'DailyTriageController@index')->name('triage');
Route::post('/guardar-triage','DailyTriageController@store')->name('store.triage');

//reporte de covid
Route::get('/reporte-de-covid-19', 'CaseReportController@index')->name('report.case');
Route::post('/guardar-reporte-','CaseReportController@store')->name('store.report');

//verificación diaria
Route::get('/verificación-diaria', 'DailyCheckController@index')->name('daily.check');
Route::post('/guardar-verificación-diaria','DailyCheckController@store')->name('store.check');


//Protocolos
Route::get('/protocolos', 'ProtocolController@index')->name('protocol');
//Noticias
Route::get('/noticias', 'NoticeController@index')->name('notice');
Route::get('/noticias-del-peru', 'NoticeController@notice')->name('notice.index');
Route::get('/comunicacion-', 'NoticeController@comunication')->name('comunication');



//Ficha sintomatológica
Route::get('/file', 'InfoController@file')->name('file');
Route::post('/guardar-declaración-jurada','InfoController@storeSworn')->name('store.sworn');

//phone
Route::get('/telefonos', 'InfoController@phone')->name('phone');

//qr
Route::get('/mi-qr', 'InfoController@myQr')->name('myqr');


//autenticate
Route::get('/verification-sworn', 'HomeController@verification')->name('verification');

app/Http/Controllers/supervisor/CaseReportController.php
<?php


namespace App\Http\Controllers\supervisor;

use App\Http\Controllers\Controller;
use App\case_report;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CaseReportController extends Controller
{
    public function index()
    {
        return view('supervisor.report.index');
    }
    public function review($date=0)
    {   
        if ($date==0) {
            $date=date('Y-m-d');
        }

        $reviews=case_report::join('users','users.id','case_reports.users_id')
        ->select('users.name','case_reports.created_at','case_reports.id as id')
        ->whereDate('case_reports.created_at',$date)
        ->orderBy('id','desc')->simplePaginate(4);

        return view('supervisor.report.report_review',compact('reviews'))
        ->with('date',$date);
    }
    public function filter($id)
    {   

        $reviews=case_report::join('users','users.id','case_reports.users_id')
        ->select('users.name','case_reports.*')
        ->where('case_reports.id',$id)
        ->orderBy('id','desc')->simplePaginate(4);

        return view('supervisor.report.report_filter',compact('reviews'))
        ->with('id',$id);
    }
}

app/Http/Controllers/supervisor/DailyCheckController.php
<?php


namespace App\Http\Controllers\supervisor;

use App\Http\Controllers\Controller;
use App\check_has_options;
use App\check_options;
use App\daily_check;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class DailyCheckController extends Controller
{
    public function index()
    {
        $options= check_options::orderBy('id','desc')->get();
        return view('supervisor.report.daily_check',compact('options'));
    }

    public function review($date=0)
    {
      if ($date==0) {
        $date=date('Y-m-d');
    }
        //daily_check::where('created_at',$date)->get();
        //$id=$daily[0];
        $options=check_options::orderBy('id','asc')->get(); 
        
        $reviews=check_has_options::join('daily_checks','daily_checks.id','check_has_options.daily_checks_id')
        ->join('check_options','check_options.id','check_has_options.check_options_id')
        ->select(DB::raw(' count(*) AS filas,check_has_options.check_options_id AS id,DATE_FORMAT(daily_checks.created_at, "%Y-%m-%d") AS date , check_has_options.result AS result'))
        ->groupBy('id','date','result')
        ->having('date','=',$date)
        ->having('check_has_options.result','=',1)
        ->get();
        $total=daily_check::whereDate('daily_checks.created_at',$date)->count();
        $total=$total;

        return view('supervisor.report.daily_review',compact('options','reviews'))
        ->with('date',$date)
      ->with('total',$total);
    }

    public function reviewYes($id,$date)
    {
        $options=check_options::orderBy('id','desc')->get(); 
        $reviews=daily_check::join('check_has_options','daily_checks.id','check_has_options.daily_checks_id')
        ->join('users','users.id','daily_checks.users_id')
        ->select('users.name','daily_checks.created_at')
        ->whereDate('daily_checks.created_at',$date)
        ->where('check_has_options.check_options_id',$id)
        ->where('check_has_options.result',1)
        ->paginate(4);
     
        $total=$options->count();
        
        return view('supervisor.report.daily_review_list',compact('options','reviews'))
      ->with('total',$total);
    }
    public function reviewNo($id,$date)
    {
        $options=daily_check::whereDate('daily_checks.created_at',$date)->get(); 
        $reviews=daily_check::join('check_has_options','daily_checks.id','check_has_options.daily_checks_id')
        ->join('users','users.id','daily_checks.users_id')
        ->select('users.name','daily_checks.created_at')
        ->whereDate('daily_checks.created_at',$date)
        ->where('check_has_options.check_options_id',$id)
        ->where('check_has_options.result',0)
        ->paginate(4);
        $total=$options->count();
        
        return view('supervisor.report.daily_review_list_no',compact('options','reviews'))
      ->with('total',$total);
    }
   
}

app/Http/Controllers/supervisor/DailyTriageController.php
<?php


namespace App\Http\Controllers\supervisor;

use App\Http\Controllers\Controller;
use App\check_options;
use App\daily_triage;
use App\triage_has_simptoms;
use App\triage_simptoms;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DailyTriageController extends Controller
{
    public function index()
    {
         return view('supervisor.triage.index');
    }

    public function review($date=0)
    {
      if ($date==0) {
        $date=date('Y-m-d');
    }

    $reviews=daily_triage::join('users','users.id','daily_triages.users_id')
    ->select('users.name','daily_triages.created_at','daily_triages.id AS id')
    ->whereDate('daily_triages.created_at',$date)
    ->orderBy('id','desc')->paginate(4);

    return view('supervisor.triage.triage_review',compact('reviews'))
    ->with('date',$date);
       
    }

    public function filter($id)
    {   

        $reviews=daily_triage::join('users','users.id','daily_triages.users_id')
        ->select('users.name','daily_triages.*')
        ->where('daily_triages.id',$id)
        ->orderBy('daily_triages.id','desc')->first();

        $options=triage_has_simptoms::join('triage_symptoms','triage_symptoms.id','triage_has_symptoms.triage_symptoms_id')
        ->where('triage_has_symptoms.daily_triages_id',$id)
        ->orderBy('triage_has_symptoms.daily_triages_id','asc')->get();

        return view('supervisor.triage.triage_filter',compact('reviews','options'))
        ->with('id',$id);
    }

}

app/Http/Controllers/supervisor/EmergencyPhoneController.php
<?php


namespace App\Http\Controllers\supervisor;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class EmergencyPhoneController extends Controller
{
    //
}

app/Http/Controllers/supervisor/HomeController.php
<?php



namespace App\Http\Controllers\supervisor;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('welcome');
    }
    public function panel()
    {       
         $user = Auth::user();

         if ($user->hasRole('admin')) {
          return redirect()->route('admin');
           # code...
         }
         if ($user->hasRole('supervisor')) {
          return redirect()->route('supervisor');
          # code...
         }
         if ($user->hasRole('user')) {
          return redirect()->route('usuario');
           # code...
         }
     
    }

    public function usuario()
    {
        return view("public.index");
    }
    public function admin()
    {
        return view("admin.index");
    }
    public function supervisor()
    {
        return view("supervisor.index");

    }
}

app/Http/Controllers/supervisor/NoticeController.php
<?php


namespace App\Http\Controllers\supervisor;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class NoticeController extends Controller
{
    public function index()
    {
        return view('public.notice.index');
    }
}

app/Http/Controllers/supervisor/ProtocolController.php
<?php


namespace App\Http\Controllers\supervisor;

use App\Http\Controllers\Controller;
use App\protocol;
use App\protocol_has_report;
use Illuminate\Http\Request;

class ProtocolController extends Controller
{
    public function index()
    {
        $protocols= protocol::with('reports')->orderBy('id','DESC')->get();

        $reports=protocol_has_report::all();
        return view('public.protocol.index',compact('protocols','reports'));
    }
}

app/Http/Controllers/supervisor/ProtocolHasReportController.php
<?php


namespace App\Http\Controllers\supervisor;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ProtocolHasReportController extends Controller
{
    //
}

resources/views/supervisor/triage/triage_filter.blade.php
@extends('layouts.views')
@section('css')
    <style>
      
      .line-sep{
       border-style: solid;
       background-color: blue;
       height: 2px;
    }

   .opa-rec {
       opacity: 0.9;
       color: black;
       margin: 15px;
      
   }

   .font-gr{
       font-weight: 750;
   }
   
   .Informacion_Personal {
       filter: drop-shadow(3px 3px 3px rgba(0, 0, 0, 0.2));
       overflow: visible;
       white-space: nowrap;
       text-align: left;
       font-family: Segoe UI;
       font-style: normal;
       font-weight: bold;
       font-size: 18px;
       color: rgba(0,0,0,1);
   }

   .ID1_Cmo_te_sientes_hoy_Indica_ {
       filter: drop-shadow(2px 2px 2px rgba(0, 0, 0, 0.2));
       text-align: left;
       font-family: Segoe UI;
       font-style: normal;
       font-weight: bold;
       font-size: 13px;
       color: rgba(0,0,0,1);
   }

   .rect-ps1{
       position: relative;
       top: 40px; left: 40px;
   }

   .btn.btn-primary {
       background: #007eea !important;
       border-color: #007eea !important;
   }
   .si-primer-pregunta{
        display: flex;
   }
   .Icon_awesome-arrow-left{
        overflow: visible;
		position: relative;
		width: 7%;
		height: 7%;
        left: 20%;
        top: -5%;
        margin: 0%;
        color: azure !important;
   }
   #Icon_awesome-arrow-left{
    fill: rgba(255,255,255,1);

   }
   #Icon_awesome-arrow-left:hover{
    fill: rgb(24, 21, 21);

   }
   
    .otro-pregunta-5{
    display: flex;
   }
   .title{
    font-size: 130%;
    margin-left: 10%;

}
   
@media (max-width: 350px) {
 
    .title{
    font-size: 120%;
}
}
    </style>
@endsection
@section('content')
<!--Encabezado inicial -->

<div class="row mb-4 mt-4 bg-secondary text-white ">
  <div class="col-2 col-sm-2 col-md-2">
      <button onclick="location.href='{{route('supervisor.triage.review') }}'" style="background-color: transparent; width:100%; height:100%; border:none;" type="button" class="text-left">
    <i class="fa fa-arrow-left fa-2x" aria-hidden="true" style="color:#ffffff;"></i>
      </button>
  </div>
  <div class="col-8 col-sm-8 col-md-8 ">
    <p class="text-center font-weight-bold title">Triaje diario registrado</p>
  </div>
  <div class="col-2 col-sm-2 col-md-2">
  </div>
</div>
<!--Fin Encabezado inicial -->


        <form  method="POST" action="{{route('store.triage')}}" onsubmit="save(event)" id="form_check">
            @csrf
            <section  id="section_check" >

              <div class="opa-rec" >
                <div  class="p-3 bg-secondary card text-black" id="mb-inferior">
               
              @include('supervisor.partials.data-triage')
           
            <input type="hidden" value="No" id="contact" name="contact">

          
</div>

</div>
</section>

<section  id="section_verification" style="display: none">
  @include('public.partials.confirm')

</section>
</form>
<section id="section_success" style="display: none">
  @include('public.partials.success')
  </section>
@endsection

@section('scripts')
<script type="text/javascript" src="{{asset('js/sweetalert.min.js')}}"></script> 

<script>
    var option=[];
    function change_other(a){
        if ($(a).prop('checked')==true) {
        $("#input_symptom").attr("disabled",false);

        }else{
            $("#input_symptom").attr("disabled",true);
            $("#input_symptom").val('');

        }
    }
    function change_contact(a) {
      if ($(a).text()=='SI') {
          $(a).addClass('active');
          $("#btn_contact_no").removeClass('active');
          $("#contact").val('Si')
      }else{
        $(a).addClass('active');
        $("#btn_contact_si").removeClass('active');
        $("#contact").val('No')

      }
    }
   
    function send() {
        $("#section_check").css('display','none');
        $("#section_verification").css('display','block');
    }
    function save(e) {
       e.preventDefault();
       var formdata = new FormData($("#form_check")[0]);
       $.ajax({
           url         : "{{route('store.triage')}}",
           data        : formdata,
           cache       : false,
           contentType : false,
           processData : false,
           type        : 'POST',
           dataType:"JSON",
           beforeSend:function() {
             swal("Por favor espera,tu petición se está procesando!", {
               buttons: false,
               
             });
           },
           success: function(data, textStatus, jqXHR){
               swal.close();
               if (data.result != null) {
                 let msg= "La información se ha registrado correctamente";
                 $("#date_success").text(data.date);
                 $("#time_success").text(data.time);
                 $("#section_verification").css('display','none');
                 $("#section_success").css('display','block');
               }else{
                 swal("Ups!",data.message,"error");   
               }

             },
             error:function(data,message,res){
               swal("ups!","Hubo un error al procesar tu petición,vuelve a intentar por favor","error");
             },
             statusCode:{
               422:function(data) {
           swal("Ups!","El número de caso ingresado ya existe,por favor ingrese uno nuevo","error");
               }
             }
       }); 
 }
 function back() {
     
    $("#section_check").css('display','block');
    $("#section_verification").css('display','none');

 }
</script>
@endsection

resources/views/supervisor/triage/triage_review.blade.php
@extends('layouts.views')
@section('css')
<style>
    
    .line-sep{
       border-style: solid;
       background-color: blue;
       height: 2px;
    }

   .opa-rec {
       opacity: 0.9;
       color: black;
       margin: 15px;
      
   }

   .font-gr{
       font-weight: 750;
   }
   
   .Informacion_Personal {
       filter: drop-shadow(3px 3px 3px rgba(0, 0, 0, 0.2));
       overflow: visible;
       white-space: nowrap;
       text-align: left;
       font-family: Segoe UI;
       font-style: normal;
       font-weight: bold;
       font-size: 18px;
       color: rgba(0,0,0,1);
   }

   .ID1_Cmo_te_sientes_hoy_Indica_ {
       filter: drop-shadow(2px 2px 2px rgba(0, 0, 0, 0.2));
       text-align: left;
       font-family: Segoe UI;
       font-style: normal;
       font-weight: bold;
       font-size: 13px;
       color: rgba(0,0,0,1);
   }

   .rect-ps1{
       position: relative;
       top: 40px; left: 40px;
   }

   .btn.btn-primary {
       background: #007eea !important;
       border-color: #007eea !important;
   }
.Icon_awesome-arrow-left{
        overflow: visible;
		position: relative;
		width: 7%;
		height: 7%;
        left: 20%;
        top: -5%;
        margin: 0%;
        color: azure !important;
   }
   #Icon_awesome-arrow-left{
    fill: rgba(255,255,255,1);

   }
   #Icon_awesome-arrow-left:hover{
    fill: rgb(24, 21, 21);

   }
   .card{
       border-radius: 10% !important;
       background-color: rgba(204,204,204,0.8) !important;
   }
   .title{
    font-size: 130%;
    margin-left: 20%;
}
   
@media (max-width: 350px) {
 
    .title{
    font-size: 120%;
        


}
}
   </style>
@endsection
@section('content')
<!--Encabezado inicial -->

<div class="row mb-4 mt-4 bg-secondary text-white ">
    <div class="col-2 col-sm-2 col-md-1">
        <button onclick="location.href='{{route('supervisor.triage') }}'" style="background-color: transparent; width:100%; height:100%; border:none;" type="button" class="text-left">
      <i class="fa fa-arrow-left fa-2x" aria-hidden="true" style="color:#ffffff;"></i>
        </button>
    </div>
    <div class="col-8 col-sm-8 col-md-8 ">
        <p class="text-center font-weight-bold title">Triajes registrados</p>
    </div>
    <div class="col-2 col-sm-2 col-md-1">
    </div>
  </div>
<!--Fin Encabezado inicial -->
<form action="{{route('supervisor.triage')}}" method="POST" onsubmit="save(event)" id="form_check">
<div class="ml-3 d-flex">
    <div class="input-group">
    <label for="">Indique la fecha</label>
    <input type="date" name="date" class="form-control col-6" value="{{$date}}" onchange="select_date(this)">
    </div>
</div>
<section id="section_check">
<div class="opa-rec" >
    <div  class="p-3 bg-secondary card text-black" id="mb-inferior">
        <hr class="line-sep">
        @foreach ($reviews as $review)
    <a href="{{route('supervisor.triage.filter',$review->id)}}" style="color: #000000; font-size: 120%;">
        <div>
            <div>
                <span>Registrado por:</span>
            <span>{{$review->name}}</span>
            </div>
        <div>
            <span>Fecha:</span>
            <span>{{date('Y-m-d', strtotime($review->created_at))}}</span>
        </div>
        <div>
            <span>Hora:</span>
            <span>{{date('H:i:s', strtotime($review->created_at))}}</span>
        </div>
        <hr class="line-sep">
        </div>
    </a>
        @endforeach
            @csrf
        <div id="option"></div>
        <br>
        <div class="mx-auto">
            <ul class="pagination ">
            <li ><a class="last_page btn " href="javascript:;">Página {{$reviews->currentPage()}} de {{$reviews->lastPage()}}</a></li>
                <li ><a class="last_page btn btn-color" style="background-color: rgba(67,32,255,1);color:#ffffff;border-radius: 10px;" href="{{$reviews->previousPageUrl() }}"><i class="fa fa-chevron-left"></i></a></li>
                <li><a class="next_page btn btn-color" style="background-color: rgba(67,32,255,1);color:#ffffff; border-radius: 10px;" href="{{$reviews->nextPageUrl() }}"><i class="fa fa-chevron-right"></i></a></li>
              </ul>
        </div>
    </div>
		
</div>
</section>
<section id="section_verification" style="display: none">
    @include('public.partials.confirm')

</section>
</form>

<section id="section_success" style="display: none">
    @include('public.partials.success')
</section>
@endsection
@section('scripts')
<script>
    function select_date(a) {
       url='{{route('supervisor.triage.review',["date"=> 0])}}';
       url=url.replace('0',$(a).val());
       location.href=url;
        
    }
</script>
@endsection