routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
define('STDIN',fopen("php://stdin","r"));
Route::get('install', function() {
    Artisan::call('migrate',['--force'=>true,'--seed'=>true]);
});
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::namespace('admin')->name('admin.')->middleware(['auth'])->group(function(){
    Route::get('/admin/triage-diario-index', 'DailyTriageController@index')->name('triage');
    Route::get('/admin/traige-diario-review-/{date?}', 'DailyTriageController@review')->name('triage.review');
    Route::get('/admin/traige-diario-filter-/{id?}', 'DailyTriageController@filter')->name('triage.filter');
    Route::get('/admin/traige-diario/estadisticas/{date?}', 'DailyTriageController@chart')->name('triage.chart');
    Route::get('/admin/traige-diario/send-email/{email}', 'DailyTriageController@sendEmail')->name('triage.send.email');
    Route::get('/admin/triage/enviar-email',function (){
        return view('admin.report.daily-check-email');
    })->name('triage.email');
    //reporte de covid
    Route::get('/admin/reporte-de-covid-19-', 'CaseReportController@index')->name('report.case');
    Route::get('/admin/reporte-de-covid-19-review/{date?}', 'CaseReportController@review')->name('report.case.review');
    Route::get('/admin/reporte-de-covid-19-filter/{id?}', 'CaseReportController@filter')->name('report.case.filter');
    
    //verificación diaria
    Route::get('/admin/verificación-diaria', 'DailyCheckController@index')->name('daily.check');
    Route::get('/admin/verificación-diaria-review', 'DailyCheckController@review')->name('daily.check.review');
    Route::get('/admin/check-si/{id}/{date}', 'DailyCheckController@reviewYes')->name('daily.check.review.yes');
    Route::get('/admin/check-no/{id}/{date}', 'DailyCheckController@reviewNo')->name('daily.check.review.no');
    Route::get('/admin/estadísticas/{date?}', 'DailyCheckController@chart')->name('daily.check.chart');
    Route::get('/admin/enviar-email',function (){
        return view('admin.report.daily-check-email');
    })->name('daily.check.email');
    Route::get('/admin/daily/send-email/{email}', 'InfoController@sendEmailDaily')->name('daily.check.send.email');

    Route::get('/admin/mi-qr', 'InfoController@myQr')->name('myqr');
    //Protocolos
    Route::get('/admin/protocolos', 'ProtocolController@index')->name('protocol');
    //Noticias
    Route::get('/admin/noticias', 'NoticeController@index')->name('notice');
    //Ficha sintomatológica
    Route::get('/admin/file', 'InfoController@file')->name('file');
    Route::get('/admin/file-review/{date?}', 'InfoController@review')->name('file.review');
    Route::get('/admin/file-filter/{id?}', 'InfoController@filter')->name('file.filter');
    Route::get('/admin/file-excel',function(){
        return view('admin.report.report-excel-send');
    })->name('file.send-excel');
    Route::get('/admin/send-email/{email}', 'InfoController@sendEmail')->name('file.send.email');

    //phone
    Route::get('admin/telefonos', 'InfoController@phone')->name('phone');
});

Route::namespace('supervisor')->name('supervisor.')->middleware(['auth'])->group(function () {
   //traige
Route::get('/supervisor/traige-diario-view', 'DailyTriageController@index')->name('triage');
Route::get('/supervisor/traige-diario-review/{date?}', 'DailyTriageController@review')->name('triage.review');
Route::get('/supervisor/traige-diario-filter/{id?}', 'DailyTriageController@filter')->name('triage.filter');

//reporte de covid
Route::get('/supervisor/reporte-de-covid-19-', 'CaseReportController@index')->name('report.case');
Route::get('/supervisor/reporte-de-covid-19-review/{date?}', 'CaseReportController@review')->name('report.case.review');
Route::get('/supervisor/reporte-de-covid-19-filter/{id?}', 'CaseReportController@filter')->name('report.case.filter');

//verificación diaria
Route::get('/supervisor/verificación-diaria', 'DailyCheckController@index')->name('daily.check');
Route::get('/supervisor/verificación-diaria-review-/{date?}', 'DailyCheckController@review')->name('daily.check.review');
Route::get('/supervisor/check-si/{id}/{date}', 'DailyCheckController@reviewYes')->name('daily.check.review.yes');
Route::get('/supervisor/check-no/{id}/{date}', 'DailyCheckController@reviewNo')->name('daily.check.review.no');

Route::get('/supervisor/mi-qr', 'InfoController@myQr')->name('myqr');
//Protocolos
Route::get('/supervisor/protocolos', 'ProtocolController@index')->name('protocol');
//Noticias
Route::get('/supervisor/noticias', 'NoticeController@index')->name('notice');
//Ficha sintomatológica
Route::get('/supervisor/file', 'InfoController@file')->name('file');
Route::get('/supervisor/file-review/{date?}', 'InfoController@review')->name('file.review');
Route::get('/supervisor/file-filter/{id?}', 'InfoController@filter')->name('file.filter');



Route::get('/lector-qr', 'InfoController@lectorQr')->name('lector.qr');
Route::post('/guardar-qr', 'InfoController@saveQr')->name('store.qr');
Route::get('/historial-qr/{date?}', 'InfoController@reviewQr')->name('qr.review');


});
/*Route::namespace('supervisor')->middleware(['auth','supervisor'])->group(function(){


});*/

Route::get('/home', 'HomeController@panel')->name('home');
Route::get('/admin', 'HomeController@admin')->name('admin');
Route::get('/supervisor', 'HomeController@supervisor')->name('supervisor');
Route::get('/inicio', 'HomeController@usuario')->name('usuario');

//traige
Route::get('/traige-diario-', 'DailyTriageController@index')->name('triage');
Route::post('/guardar-triage','DailyTriageController@store')->name('store.triage');

//reporte de covid
Route::get('/reporte-de-covid-19', 'CaseReportController@index')->name('report.case');
Route::post('/guardar-reporte-','CaseReportController@store')->name('store.report');

//verificación diaria
Route::get('/verificación-diaria', 'DailyCheckController@index')->name('daily.check');
Route::post('/guardar-verificación-diaria','DailyCheckController@store')->name('store.check');


//Protocolos
Route::get('/protocolos', 'ProtocolController@index')->name('protocol');
//Noticias
Route::get('/noticias', 'NoticeController@index')->name('notice');
Route::get('/noticias-del-peru', 'NoticeController@notice')->name('notice.index');
Route::get('/comunicacion-', 'NoticeController@comunication')->name('comunication');



//Ficha sintomatológica
Route::get('/file', 'InfoController@file')->name('file');
Route::post('/guardar-declaración-jurada','InfoController@storeSworn')->name('store.sworn');

//phone
Route::get('/telefonos', 'InfoController@phone')->name('phone');

//qr
Route::get('/mi-qr', 'InfoController@myQr')->name('myqr');


//autenticate
Route::get('/verification-sworn', 'HomeController@verification')->name('verification');

resources/views/admin/report/daily-check-email.blade.php
@extends('layouts.views')
@section('css')
<style>
	
	#Rectngulo_49 {
		fill: rgba(0,204,170,0.498);
	}
	.Rectngulo_49 {
		position: absolute;
		overflow: visible;
		width: 200px;
        height: 200px;
        left: 20%;
        top: 18%;
}
	}
    
	#Rect {
		fill: rgba(0,204,170,0.498);
	}
	.Rectngulo_50 {
		position: absolute;
		overflow: visible;
		width: 200px;
        height: 200px;
        left: 20%;
        top: 60%;
        fill: rgba(0,204,170,0.498)

	}
	#Icon_awesome-clipboard-list {
		fill: rgba(255,255,255,1);
	}
	.Icon_awesome-clipboard-list {
		overflow: visible;
		position: relative;
        width: 40%;
        height: 40%;
		margin-top: 0;

		transform: matrix(1,0,0,1,0,0);
	}

	#Icon_material-find-in-page {
		fill: rgba(255,255,255,1);
	}
	.Icon_material-find-in-page {
		overflow: visible;
		position: relative;
		width: 40%;
        height: 40%;
		transform: matrix(1,0,0,1,0,0);
	}
	.Icon_awesome-arrow-left{
        overflow: visible;
		position: relative;
		width: 90%;
		height: 5%;
        left: 20%;
        top: -5%;
        margin: 0%;
        color: azure !important;
   }
   #Icon_awesome{
    fill: rgba(255,255,255,1);

   }
   #Icon_awesome-arrow-left:hover{
    fill: rgb(24, 21, 21);

   }
   .btn{
	    white-space: nowrap;
		text-align: center;
		font-family: Segoe UI;
		font-style: normal;
		font-weight: bold;
		font-size: 130%;
		color: rgba(255,255,255,1);
		background-color: rgba(0,170,204,0.498);
		width: 65%;
		height: 95%;
   }
   #Icon_simple-microsoftexcel {
		fill: rgba(255,255,255,1);
	}
	.Icon_simple-microsoftexcel {
		overflow: visible;
		position: relative;
		
		transform: matrix(1,0,0,1,0,0);
	}
    #Enviar {
    white-space: nowrap;
    text-align: center;
    font-family: SegoeUI;
    font-style: normal;
    font-weight: normal;
    font-size: 20px;
    color: rgba(255,255,255,1);
    border-radius: 7px !important;
    
}
   </style>

@endsection
@section('content')
<section id="section_verification">


<div class="row mb-4 mt-4 bg-secondary text-white ">
    <div class="col-2 col-sm-2 col-md-2">
        <button onclick="location.href='{{route('admin.daily.check.chart') }}'" style="background-color: transparent; height:100%; border:none;" type="button" class="text-left">
			<i class="fa fa-arrow-left fa-2x" style="color:#ffffff;"></i>
        </button>
    </div>
    <div class="col-8 col-sm-8 col-md-8 text-center align-self-center">
        <p class="text-center font-weight-bold" style="font-size: 110%">Revisión  de verificación diaria</p>
	</div>
    <div class="col-2 col-sm-2 col-md-2">
	</div>
  </div>
  
	<div class="row ">

		<div class="col-lg-1 col-md-1 col-xs-1 col-1 mr-2">
		</div>
	
		<div class="col-10 col-sm-10 text-center">
			<h5 class="text-center text-light" >Exportación a excel</h5>
			<p>Por favor, ingrese su correo electrónico para poder
			enviarle la tabla de datos de esta función
			 registrados hasta la fecha de hoy.</p>
			 <br><br>
				 <div class="form-group text-center">
					 <input type="text" class="form-control" name="email" id="email" type="mail" placeholder="correo electrónico">
				 </div>
				 <div class="form-group text-center mb-4">
					<button class="btn " style="background-color: rgba(67,32,255,1) !important; margin-bottom: 30px;"  type="button" onclick="send();" id="btn_enviar">Enviar</button>
	
				 </div>
				 <div class="form-group mt-4">
					<a href="#" class="text-center "><img src="{{asset('img/logo.png')}}"  style="width: 40%"></a>
	
				 </div>
	
		</div>
		<div class="col-lg-1 col-md-1 col-xs-1 col-1 mr-2">
		</div>
	  </div>
</section>

<section id="section_success" style="display: none">
	@include('admin.partials.success')

</section>
@endsection

@section('scripts')
<script type="text/javascript" src="{{asset('js/sweetalert.min.js')}}"></script> 

<script>
	
function send(){
		let url="{{route('admin.daily.check.send.email',0)}}";
		url=url.replace('0',$("#email").val())
       $.ajax({
           url         : url,
           type        : 'GET',
           dataType:"JSON",
           beforeSend:function() {
             swal("Por favor espera,tu petición se está procesando!", {
               buttons: false,
               
             });
           },
           success: function(data, textStatus, jqXHR){
               swal.close();
               if (data.result != null) {
                 let msg= "La información se ha registrado correctamente";
                 $("#date_success").text(data.date);
                 $("#time_success").text(data.time);
                 $("#section_verification").css('display','none');
                 $("#section_success").css('display','block');
               }else{
                 swal("Ups!",data.message,"error");   
               }

             },
             error:function(data,message,res){
               swal("ups!","Hubo un error al procesar tu petición,vuelve a intentar por favor","error");
             },
       
       }); 
}
</script>	
@endsection

resources/views/admin/report/daily_review.blade.php
@extends('layouts.views')
@section('css')
<style>
    
    .line-sep{
       border-style: solid;
       background-color: blue;
       height: 2px;
    }

   .opa-rec {
       opacity: 0.9;
       color: black;
       margin: 15px;
      
   }

   .font-gr{
       font-weight: 750;
   }
   
   .Informacion_Personal {
       filter: drop-shadow(3px 3px 3px rgba(0, 0, 0, 0.2));
       overflow: visible;
       white-space: nowrap;
       text-align: left;
       font-family: Segoe UI;
       font-style: normal;
       font-weight: bold;
       font-size: 18px;
       color: rgba(0,0,0,1);
   }

   .ID1_Cmo_te_sientes_hoy_Indica_ {
       filter: drop-shadow(2px 2px 2px rgba(0, 0, 0, 0.2));
       text-align: left;
       font-family: Segoe UI;
       font-style: normal;
       font-weight: bold;
       font-size: 13px;
       color: rgba(0,0,0,1);
   }

   .rect-ps1{
       position: relative;
       top: 40px; left: 40px;
   }

   .btn.btn-primary {
       background: #007eea !important;
       border-color: #007eea !important;
   }
   .Icon_awesome-arrow-left{
        overflow: visible;
		position: relative;
		width: 100%;
		height: 5%;
        left: 20%;
        top: -5%;
        margin: 0%;
        color: azure !important;
   }
   #Icon_awesome-arrow-left{
    fill: rgba(255,255,255,1);

   }
   #Icon_awesome-arrow-left:hover{
    fill: rgb(24, 21, 21);

   }
   .btn-success{
    width: 100px;
    height: 30px;
    filter: drop-shadow(5px 5px 5px rgba(0, 102, 81, 1));
    font-family: Segoe UI;
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    border: none;
    background-color: rgba(0,204,162,1) !important;

}
 .active{
    background-color: rgb(7, 131, 106) !important;
}
   </style>
@endsection
@section('content')
<!--Encabezado inicial -->

<div class="row mb-4 mt-4 bg-secondary text-white ">
    <div class="col-3 col-xs-3 col-md-3">
        <button onclick="location.href='{{route('supervisor.daily.check') }}'" style="background-color: transparent; width:100%; height:100%; border:none;" type="button" class="text-left">
			<i class="fa fa-arrow-left fa-2x" style="color:#ffffff;"></i>
        </button>
    </div>
    <div class="col-7 col-xs-7 col-md-7">
        <p class="text-center font-weight-bold" style="font-size: 130%">Revisión  de verificación diaria</p>
    </div>
  </div>
<!--Fin Encabezado inicial -->
<div class="ml-3 d-flex">
    <div class="input-group">
    <label for="">Indique la fecha</label>
    <input type="date" name="date" class="form-control col-6" value="{{$date}}" onchange="select_date(this)">
    </div>
</div>
<form action="{{route('store.check')}}" method="POST" onsubmit="save(event)" id="form_check">

<section id="section_check">
<div class="opa-rec" >
    <div  class="p-3 bg-secondary card text-black" id="mb-inferior">
    
        @php
        $count=1;   
       @endphp
    
        @foreach ($options as $option)
        <div class="ID1_Cmo_te_sientes_hoy_Indica_ mb-4">
        <span class="font-gr"> {{$count}}.{{$option->name}}</span>
            <div class="d-flex justify-content-around">
                <div class="col-3 col-sm-3">
                    <input type="radio" disabled checked >SI
                </div>
                <div class="col-3 col-sm-3">
                    <input type="radio" disabled   checked >NO
                </div>
            </div>

            <div class="d-flex justify-content-around">
                @php
                $aux=$total;
                $row=0;
                $link=route('supervisor.daily.check.review.yes',['id'=>$option->id,'date'=>$date]);

                 @endphp
                   @foreach ($reviews as $review)
                   @php
                   @endphp
                   @if ($review->id == $option->id)
                   @php
                   $row=$review->filas;
                   $aux=(int) $total-$review->filas;
                    @endphp
                   @else
                   @endif
               @endforeach
               
            <a style="color: #000000" href="{{$link}}">ver {{$row}} respuestas</a>
            <a style="color: #000000" href="{{route('supervisor.daily.check.review.no',['id'=>$option->id,'date'=>$date])}}" > Ver
            {{$aux}} respuestas</span>
            </div>
        </div>
        @php
         $count=$count+1;   
        @endphp
        @endforeach
            @csrf
        <div id="option"></div>
        <br>


    </div>
		
</div>
</section>

@endsection
@section('scripts')
<script type="text/javascript" src="{{asset('js/sweetalert.min.js')}}"></script> 

<script>
    function select_date(a) {
       url='{{route('supervisor.daily.check.review',["date"=>0])}}';
       url=url.replace('0',$(a).val());
       location.href=url;
    }
</script>
@endsection

resources/views/admin/report/file_symptom_review.blade.php
@extends('layouts.views')
@section('css')
<style>
    
    .line-sep{
       border-style: solid;
       background-color: blue;
       height: 2px;
    }

   .opa-rec {
       opacity: 0.9;
       color: black;
       margin: 15px;
      
   }

   .font-gr{
       font-weight: 750;
   }
   
   .Informacion_Personal {
       filter: drop-shadow(3px 3px 3px rgba(0, 0, 0, 0.2));
       overflow: visible;
       white-space: nowrap;
       text-align: left;
       font-family: Segoe UI;
       font-style: normal;
       font-weight: bold;
       font-size: 18px;
       color: rgba(0,0,0,1);
   }

   .ID1_Cmo_te_sientes_hoy_Indica_ {
       filter: drop-shadow(2px 2px 2px rgba(0, 0, 0, 0.2));
       text-align: left;
       font-family: Segoe UI;
       font-style: normal;
       font-weight: bold;
       font-size: 13px;
       color: rgba(0,0,0,1);
   }

   .rect-ps1{
       position: relative;
       top: 40px; left: 40px;
   }

   .btn.btn-primary {
       background: #007eea !important;
       border-color: #007eea !important;
   }
.Icon_awesome-arrow-left{
        overflow: visible;
		position: relative;
		width: 7%;
		height: 7%;
        left: 20%;
        top: -5%;
        margin: 0%;
        color: azure !important;
   }
   #Icon_awesome-arrow-left{
    fill: rgba(255,255,255,1);

   }
   #Icon_awesome-arrow-left:hover{
    fill: rgb(24, 21, 21);

   }
   .card{
       border-radius: 10% !important;
       background-color: rgba(204,204,204,0.8) !important;
   }
   </style>
@endsection
@section('content')
<!--Encabezado inicial -->

<div class="row mb-4 mt-4 bg-secondary text-white ">
    <div class="col-3 col-sm-3 col-md-3">
        <a href="{{route('supervisor.triage')}}">
            <svg  class="Icon_awesome-arrow-left" viewBox="-9.004 -0 10 10" >
                <path id="Icon_awesome-arrow-left"  d="M 41.50252532958984 68.31076812744141 L 37.92483139038086 71.88845062255859 C 36.40995788574219 73.40333557128906 33.96036529541016 73.40333557128906 32.46160125732422 71.88845062255859 L 1.13264262676239 40.57561111450195 C -0.382235050201416 39.06072998046875 -0.382235050201416 36.61114883422852 1.13264262676239 35.11238479614258 L 32.46160125732422 3.78342342376709 C 33.97648239135742 2.268545866012573 36.42607116699219 2.268545866012573 37.92483139038086 3.78342342376709 L 41.50252532958984 7.361112594604492 C 43.03351593017578 8.892107009887695 43.00128173828125 11.39004421234131 41.43805694580078 12.88880634307861 L 22.01861572265625 31.3896541595459 L 68.33519744873047 31.3896541595459 C 70.47857666015625 31.3896541595459 72.20296478271484 33.11403274536133 72.20296478271484 35.25742340087891 L 72.20296478271484 40.41445541381836 C 72.20296478271484 42.55784606933594 70.47857666015625 44.28223037719727 68.33519744873047 44.28223037719727 L 22.01861572265625 44.28223037719727 L 41.43805694580078 62.7830696105957 C 43.01739501953125 64.28183746337891 43.04962921142578 66.77977752685547 41.50252532958984 68.31076812744141 Z">
                </path>
            </svg>
        </a>
    </div>
    <div class="col-7 col-sm-7 col-md-7">
        <p class="text-center font-weight-bold">Fichas sintomatológicas registradas</p>
    </div>
</div>
<!--Fin Encabezado inicial -->
<form action="{{route('supervisor.file')}}" method="POST" onsubmit="save(event)" id="form_check">
<div class="ml-3 d-flex">
    <div class="input-group">
    <label for="">Indique la fecha</label>
    <input type="date" name="date" class="form-control col-6" value="{{$date}}" onchange="select_date(this)">
    </div>
</div>
<section id="section_check">
<div class="opa-rec" >
    <div  class="p-3 bg-secondary card text-black" id="mb-inferior">
        <hr class="line-sep">
        @foreach ($reviews as $review)
    <a href="{{route('supervisor.file.filter',$review->id)}}" style="color: #000000; font-size: 120%;">
        <div>
            <div>
                <span>Registrado por:</span>
            <span>{{$review->name}}</span>
            </div>
        <div>
            <span>Fecha:</span>
            <span>{{date('Y-m-d', strtotime($review->created_at))}}</span>
        </div>
        <div>
            <span>Hora:</span>
            <span>{{date('H:i:s', strtotime($review->created_at))}}</span>
        </div>
        <hr class="line-sep">
        </div>
    </a>
        @endforeach
            @csrf
        <div id="option"></div>
        <br>
        <div class="mx-auto">
            <ul class="pagination ">
                <li ><a class="last_page btn btn-primary" href="{{$reviews->previousPageUrl() }}"><i class="fa fa-chevron-left"></i></a></li>
                <li ><a class="last_page btn " href="javascript:;">{{$reviews->currentPage()}}</a></li>
                <li><a class="next_page btn btn-primary" href="{{$reviews->nextPageUrl() }}"><i class="fa fa-chevron-right"></i></a></li>
              </ul>
        </div>
 
    </div>
		
</div>
</section>
<section id="section_verification" style="display: none">
    @include('public.partials.confirm')

</section>
</form>

<section id="section_success" style="display: none">
    @include('public.partials.success')
</section>
@endsection
@section('scripts')
<script>
    function select_date(a) {
       url='{{route('supervisor.file.review',["date"=> 0])}}';
       url=url.replace('0',$(a).val());
       location.href=url;
        
    }
</script>
@endsection

resources/views/admin/report/report_review.blade.php
@extends('layouts.views')
@section('css')
<style>
    
    .line-sep{
       border-style: solid;
       background-color: blue;
       height: 2px;
    }

   .opa-rec {
       opacity: 0.9;
       color: black;
       margin: 15px;
      
   }

   .font-gr{
       font-weight: 750;
   }
   
   .Informacion_Personal {
       filter: drop-shadow(3px 3px 3px rgba(0, 0, 0, 0.2));
       overflow: visible;
       white-space: nowrap;
       text-align: left;
       font-family: Segoe UI;
       font-style: normal;
       font-weight: bold;
       font-size: 18px;
       color: rgba(0,0,0,1);
   }

   .ID1_Cmo_te_sientes_hoy_Indica_ {
       filter: drop-shadow(2px 2px 2px rgba(0, 0, 0, 0.2));
       text-align: left;
       font-family: Segoe UI;
       font-style: normal;
       font-weight: bold;
       font-size: 13px;
       color: rgba(0,0,0,1);
   }

   .rect-ps1{
       position: relative;
       top: 40px; left: 40px;
   }

   .btn.btn-primary {
       background: #007eea !important;
       border-color: #007eea !important;
   }
.Icon_awesome-arrow-left{
        overflow: visible;
		position: relative;
		width: 7%;
		height: 7%;
        left: 20%;
        top: -5%;
        margin: 0%;
        color: azure !important;
   }
   #Icon_awesome-arrow-left{
    fill: rgba(255,255,255,1);

   }
   #Icon_awesome-arrow-left:hover{
    fill: rgb(24, 21, 21);

   }
   .card{
       border-radius: 10% !important;
       background-color: rgba(204,204,204,0.8) !important;
   }
   </style>
@endsection
@section('content')
<!--Encabezado inicial -->

<div class="row mb-4 mt-4 bg-secondary text-white ">
    <div class="col-3 col-xs-3 col-md-3">
        <button onclick="location.href='{{route('home') }}'" style="background-color: transparent; width:100%; height:100%; border:none;" type="button" class="text-left">
			<i class="fa fa-arrow-left fa-2x" style="color:#ffffff;"></i>
        </button>
    </div>
    <div class="col-7 col-xs-7 col-md-7">
        <p class="text-center font-weight-bold " style="font-size: 110%">Reportes Registrados</p>
    </div>
  </div>
<!--Fin Encabezado inicial -->
<form action="{{route('supervisor.report.case')}}" method="POST" onsubmit="save(event)" id="form_check">
<div class="ml-3 d-flex">
    <div class="input-group">
    <label for="">Indique la fecha</label>
    <input type="date" name="date" class="form-control col-6" value="{{$date}}" onchange="select_date(this)">
    </div>
</div>
<section id="section_check">
<div class="opa-rec" >
    <div  class="p-3 bg-secondary card text-black" id="mb-inferior">
        <hr class="line-sep">
        @foreach ($reviews as $review)
    <a href="{{route('supervisor.report.case.filter',$review->id)}}" style="color: #000000; font-size: 120%;">
        <div>
            <div>
                <span>Registrado por:</span>
            <span>{{$review->name}}</span>
            </div>
        <div>
            <span>Fecha:</span>
            <span>{{date('Y-m-d', strtotime($review->created_at))}}</span>
        </div>
        <div>
            <span>Hora:</span>
            <span>{{date('H:i:s', strtotime($review->created_at))}}</span>
        </div>
        <hr class="line-sep">
        </div>
    </a>
        @endforeach
            @csrf
        <div id="option"></div>
        <br>
        <div class="mx-auto">
            <ul class="pagination ">
                <li ><a class="last_page btn btn-primary" href="{{$reviews->previousPageUrl() }}"><i class="fa fa-chevron-left"></i></a></li>
                <li ><a class="last_page btn " href="javascript:;">{{$reviews->currentPage()}}</a></li>
                <li><a class="next_page btn btn-primary" href="{{$reviews->nextPageUrl() }}"><i class="fa fa-chevron-right"></i></a></li>
              </ul>
        </div>
 
    </div>
		
</div>
</section>
<section id="section_verification" style="display: none">
    @include('public.partials.confirm')

</section>
</form>

<section id="section_success" style="display: none">
    @include('public.partials.success')
</section>
@endsection
@section('scripts')
<script>
    function select_date(a) {
       url='{{route('supervisor.report.case.review',["date"=> 0])}}';
       url=url.replace('0',$(a).val());
       location.href=url;
        
    }
</script>
@endsection